# command: hugo server -D --bind=0.0.0.0 --baseURL=http://192.168.0.12:1313 
baseURL: https://projects.8bitsqu.id/
languageCode: en-gb
title: Aadi | Projects
# TO DO: Update Title
theme: PaperMod
enableEmoji: true
# TO DO: Go through themes and select
# paginate: 2
permalinks:
  posts: /:year/:month/:day/:slug/

# Font Awesome icons?

imaging:
  quality: 100 # Maximum quality for compressed images
  exif:
    includeFields: "" # Include no exif data on photos
    # disableDate: true # Disable date in exif data
    # disableLatLong: true # Disable latitude and longitude in exif data

# PaperMod: very cool, keep in mind
# example config: https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/config.yml
# copyright: "Copyright Text"
params:
  # figure out params at https://github.com/adityatelange/hugo-PaperMod/
  defaultTheme: auto
  description: A personal website to show off projects and things I've done
  homeInfoParams:
    Title: |
      - Hi 👋
    Content: |
      - I'm Aadi, a software developer and home-lab hacker from London.
      - Thanks for visiting my site.
      - 
      - Here you'll find writeups on my projects and sometimes other things I find interesting
      - Get started here: [Welcome](/welcome)
      - Or find me elsewhere:
  socialIcons: # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-icons/#share-icons
    - name: github
      url: "https://github.com/supleed2"
    - name: linkedin
      url: "https://www.linkedin.com/in/aadidesai/"
    - name: keybase
      url: "https://keybase.io/aadidesai"
    - name: telegram
      url: "https://t.me/supleed2"
    - name: kofi
      url: "https://ko-fi.com/aadidesai"
  showShareButtons: custom
  shareButtons:
    - twitter
    - linkedin
    - reddit
    - facebook
    - whatsapp
    - telegram
menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: About
      weight: 2
      url: /about
    - name: Posts
      weight: 3
      url: /posts/
    - name: Contact Me
      weight: 4
      url: /contact
# archive page: content/archives.md
# ---
# title: "Archive"
# date: 2022-01-06T21:20:51Z
# draft: true
# layout: "archives"
# url: "/archives/"
# summary: archives
# ---

# Stack: VERY Clean, especially on desktop, keep in mind
# params:
